version: '3'
services:
  portfolio:
    # Dockerfileの場所
    build: 
        context: ./
        dockerfile: ./Dockerfile
    tty: true
    container_name: portfolio
    working_dir: /portfolio/project
    # ホストOSとコンテナ内でソースコードを共有する
    volumes:
      - ./project:/portfolio/project
    # コンテナ内部の3000を外部から5000でアクセスする
    ports:
      - 5000:3000
    environment:
      - HOST=0.0.0.0